language: ruby
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
notifications:
  email: false
